[package]
name = "github-readme-stats-docker"
version = "1.1.0"
edition = "2021"

[dependencies]
hyper = { version = "0.14.27", features = ["full"] }
tokio = { version = "1", features = ["full"] }
ctrlc = "3.4.1"
url = "2.4.1"
